# Generated by Django 4.0.2 on 2022-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=100)),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Other', 'Other')], default='Dog', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Uk', 'Unknown')], max_length=100)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('microchip', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('Uk', 'Unknown')], default='Unknown', max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_time', models.DateTimeField()),
            ],
        ),
    ]
