# Generated by Django 4.0.2 on 2022-02-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petfindr', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='file',
        ),
    ]
