# Generated by Django 4.0.2 on 2022-02-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfindr', '0005_pet_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
